# Generated by Django 5.2 on 2025-04-23 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teachers_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='school.department'),
        ),
    ]
