# Generated by Django 5.2 on 2025-04-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_teacher_teachers_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subjects_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='school.department'),
        ),
    ]
