# Generated by Django 5.2 on 2025-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_department_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
