# Generated by Django 5.2 on 2025-04-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_subject_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateTimeField(),
        ),
    ]
