# Generated by Django 5.2 on 2025-04-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_department_created_at_schoolclass_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attenndance',
            new_name='Attendance',
        ),
    ]
