# Generated by Django 5.2 on 2025-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_photo',
            field=models.ImageField(default='../static/images/defaultavatar.jpg', upload_to='users/'),
        ),
    ]
