# Generated by Django 5.2 on 2025-05-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name_plural': 'School Classes'},
        ),
    ]
