# Generated by Django 5.2 on 2025-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_schoolclass_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('timetable_pdf', models.FileField(upload_to='timetables/')),
                ('is_active', models.BooleanField(default=True)),
                ('class_assigned', models.ManyToManyField(to='school.schoolclass')),
            ],
        ),
    ]
