# Generated by Django 5.2 on 2025-05-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_examtimetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(choices=[('CAT 1', 'CAT 1'), ('CAT 2', 'CAT 2'), ('End Term', 'End Term')], max_length=100),
        ),
    ]
